### ISSUE TITLE
Include latest version of Framework7

### ISSUE THREAD

**Issue by PiJoules** [arvindr21/generator-framework7-phonegap#3]
Just a small request:

Could you include the latest version of Framework7 with your repository? I spent a few minutes finding out why the login screen on my app wasn't appearing and found version 0.8.7 (the version in the repo) doesn't include the selectors for login screens that are in version 0.10.0.

Thanks!

**Comment by arvindr21** [comment]
Sure. You want to submit a pull request with the changes?

**Comment by ebisbe** [comment]
@PiJoules Try now, it's using version 1.2.0

**Comment by phonzie** [comment]
@PiJoules: +1 for PR #5

**Comment by arvindr21** [comment]
Update to Framework7 - v2.2.1  `generator-framework7-phonegap@0.1.2`
