### ISSUE TITLE
Include latest version of Framework7

### ISSUE THREAD

**Issue by apps-albertozoccheddu** [arvindr21/generator-framework7-phonegap#6]
hello Arvind,
great job with your pgFW7 generator.
Can you update to the Framework7 last release ?

Last days i have some problem with the tabs component: Swipeable Tabs are not supported.

Best regards,
Alberto

**Comment by arvindr21** [comment]
Fixed it. Please update `generator-framework7-phonegap@0.1.2` to see new changes. Framework 7 updated to v2.2.1.
